services:
  aurora:
    build: .
    env_file: .env
    container_name: aurora
    ports: 
      - "${AURORA_PORT}:${AURORA_PORT}"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    restart: always
    env_file: .env
    ports: 
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s