spring.application.name=aurora
spring.datasource.url=jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}
spring.datasource.username=${POSTGRESQL_USERNAME}
spring.datasource.password=${POSTGRESQL_PASSWORD}
server.port=1234
spring.jpa.hibernate.ddl-auto=create-drop
jwt.secret.access=6b81b186b17c5922b4a4cb36f0d10f83025ba03d797dab09d44b9bc54f8e09ce
jwt.secret.refresh=6a11f506b7151ea1e16d2078c83005520abf275fa40ab20f3ba85ed158b34685
jwt.access.expire=3600000
jwt.refresh.expire=604800000
logging.level.org.springframework.security=DEBUG