spring.profiles.active=dev

spring.application.name=aurora
spring.datasource.username=postgres
spring.datasource.password=253634
server.port=1234
spring.jpa.hibernate.ddl-auto=update
jwt.secret.access=6b81b186b17c5922b4a4cb36f0d10f83025ba03d797dab09d44b9bc54f8e09ce
jwt.secret.refresh=6a11f506b7151ea1e16d2078c83005520abf275fa40ab20f3ba85ed158b34685
logging.level.org.springframework.security=DEBUG

spring.main.allow-bean-definition-overriding=true